language: python
python:
 - "3.7"
# command to install dependencies
before_install:
 - python --version
 - pip install -U pip
 - pip install -U argparse
 - pip install -U textwrap
 - pip install -U matplotlib
 - pip install -U pytest

install:
 - pip install -r rewuirements.txt
# command to run tests
script:
 - pytest
